
# ./kraz -c ./config-sample.yaml

nick: test
servers:
  - 127.0.0.1:6697
verifycert: false
channels:
  - "#test"
http:
  useragent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
ticker:
  source: "https://ca.finance.yahoo.com/quote/%s" # %s placeholder for symbol
  symbols:
    - MSFT
  interval: 1m
  excludedays:
    - 0 # Sunday
    - 6 # Saturday
  scheduleutcstart: 11
  scheduleutcstop: 22
  channel: "#test"
  executeonjoin: true
